### ISSUE TITLE
multivariate_combinatorial_Chromstar error: 

### ISSUE THREAD

**Issue by biobai** [ataudt/chromstaR#1]
Hi, 
I try to find combinatorial chromatin states in my data (in bam format),
when I run the code below: 

load(file="experiment_table_dai.RData")
library(chromstaR)
inputfolder <- file.path(dir, 'bam_files')
outputfolder <- file.path(dir, 'dai_result')

Chromstar(inputfolder, experiment.table=experiment_table_dai,
          outputfolder=outputfolder, numCPU=10, binsize=1000, mode='full')

Then i got the error: 
Running multivariate ...Error in { :
  task 1 failed - "when the supplied 'seqlengths' vector is named, the names must match the seqnames"

Please help me!

**Comment by ataudt** [comment]
Hi,
can you run Chromstar() with option numCPU=1? This will give more output and potentially a hint to what's going wrong here.
Cheers,
Aaron

**Comment by biobai** [comment]
Aaron,
Thanks for your reply.
I guess that this error is caused by the unsorted chromosome name of my genome file.
For example, the sam(bam) file contains the Arabidopsis genome chromosome length in Ensembl Plants looks like this:
@SQ     SN:Pt   LN:154478
@SQ     SN:Mt   LN:366924
@SQ     SN:4    LN:18585056
@SQ     SN:2    LN:19698289
@SQ     SN:3    LN:23459830
@SQ     SN:5    LN:26975502
@SQ     SN:1    LN:30427671

When run Chromstar() in R, the seqlevel of the GRanges reordered. So fails
"when the supplied 'seqlengths' vector is named, the names must match the seqnames".

I fixed it by revising the order of chr name in my bam files. And It works now.

Thanks for this useful tool.

Youhuang bai
