### ISSUE TITLE
Running multivariate ...Error in unserialize(socklist[[n]]) : error reading from connection

### ISSUE THREAD

**Issue by Lucas-Maciel** [ataudt/chromstaR#10]
Hi, I had a problem running Chromstar that I don't know how to resolve. Could you me please?

My exp table is:
  file             mark    condition replicate pairedEndReads controlFiles          
1 CHTH2_nodup.bam  H3K9Ac  DMSO              1 TRUE           CHTH1_nodup.bam 
2 CHTH3_nodup.bam  H3K27Ac DMSO              1 TRUE           CHTH1_nodup.bam 
3 CHTH6_nodup.bam  H3K9Ac  TH65              1 TRUE           CHTH5_nodup.bam 
4 CHTH7_nodup.bam  H3K27Ac TH65              1 TRUE           CHTH5_nodup.bam 
5 CHTH10_nodup.bam H3K9Ac  DMSO              2 TRUE           CHTH9_nodup.bam 
6 CHTH11_nodup.bam H3K27Ac DMSO              2 TRUE           CHTH9_nodup.bam 
7 CHTH14_nodup.bam H3K9Ac  TH65              2 TRUE           CHTH13_nodup.bam
8 CHTH15_nodup.bam H3K27Ac TH65              2 TRUE           CHTH13_nodup.bam

And the problem is:

> Chromstar("/work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools", exp_table,base_dir,binsize = 1000, numCPU = 8, min.mapq = 0, mode = "full")
================
Binning the data
================
Obtaining chromosome length information from file /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH2_nodup.bam ... 0.02s
Making fixed-width bins for bin size 1000 ... 0.38s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH2_nodup.bam ... 0.01s
Counting overlaps for binsize 1000 ... 33.31s
Saving to file /work/groups/schisto-th65-chipSeq/binned/H3K9Ac-DMSO-rep1_binsize1000.RData ... 0.31s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH3_nodup.bam ... 0.01s
Counting overlaps for binsize 1000 ... 35.51s
Saving to file /work/groups/schisto-th65-chipSeq/binned/H3K27Ac-DMSO-rep1_binsize1000.RData ... 0.32s
Making bam-index file ... 34.88s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH6_nodup.bam ... 0.02s
Counting overlaps for binsize 1000 ... 36.28s
Saving to file /work/groups/schisto-th65-chipSeq/binned/H3K9Ac-TH65-rep1_binsize1000.RData ... 0.32s
Making bam-index file ... 38.49s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH7_nodup.bam ... 0.03s
Counting overlaps for binsize 1000 ... 36.58s
Saving to file /work/groups/schisto-th65-chipSeq/binned/H3K27Ac-TH65-rep1_binsize1000.RData ... 0.32s
Making bam-index file ... 41s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH10_nodup.bam ... 0.02s
Counting overlaps for binsize 1000 ... 40.67s
Saving to file /work/groups/schisto-th65-chipSeq/binned/H3K9Ac-DMSO-rep2_binsize1000.RData ... 0.32s
Making bam-index file ... 38.63s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH11_nodup.bam ... 0.02s
Counting overlaps for binsize 1000 ... 36.16s
Saving to file /work/groups/schisto-th65-chipSeq/binned/H3K27Ac-DMSO-rep2_binsize1000.RData ... 0.33s
Making bam-index file ... 41.48s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH14_nodup.bam ... 0.01s
Counting overlaps for binsize 1000 ... 38.77s
Saving to file /work/groups/schisto-th65-chipSeq/binned/H3K9Ac-TH65-rep2_binsize1000.RData ... 0.32s
Making bam-index file ... 45.02s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH15_nodup.bam ... 0.01s
Counting overlaps for binsize 1000 ... 43.43s
Saving to file /work/groups/schisto-th65-chipSeq/binned/HKK27Ac-TH65-rep2_binsize1000.RData ... 0.33s
Making bam-index file ... 35.51s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH1_nodup.bam ... 0.02s
Counting overlaps for binsize 1000 ... 37.01s
Saving to file /work/groups/schisto-th65-chipSeq/binned/CHTH1_nodup.bam_binsize1000.RData ... 0.32s
Making bam-index file ... 33.97s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH5_nodup.bam ... 0.02s
Counting overlaps for binsize 1000 ... 35.52s
Saving to file /work/groups/schisto-th65-chipSeq/binned/CHTH5_nodup.bam_binsize1000.RData ... 0.31s
Making bam-index file ... 54.98s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH9_nodup.bam ... 0.02s
Counting overlaps for binsize 1000 ... 50.68s
Saving to file /work/groups/schisto-th65-chipSeq/binned/CHTH9_nodup.bam_binsize1000.RData ... 0.32s
Making bam-index file ... 54.3s
Reading header from /work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools/CHTH13_nodup.bam ... 0.02s
Counting overlaps for binsize 1000 ... 51.69s
Saving to file /work/groups/schisto-th65-chipSeq/binned/CHTH13_nodup.bam_binsize1000.RData ... 0.32s
========================
Calling univariate peaks
========================
Setting up parallel execution with 8 threads ... 2.38s
Univariate peak calling ... 79.36s
==========================
Calling multivariate peaks
==========================
mode = full
Getting coordinates ... 0.1s
Extracting read counts ... 0.87s
Getting combinatorial states ... 0.6s
Computing pre z-matrix ... 0.01s
Transfering values into z-matrix ... 1.19s
Computing inverse of correlation matrix ... 0.32s
Setting up parallel multivariate with 8 threads ... 2.66s
Running multivariate ...Error in unserialize(socklist[[n]]) : error reading from connection
In addition: Warning message:
In fixedWidthBins(chrom.lengths = chrom.lengths, chromosomes = conf[["chromosomes"]],  

Thank you for your attention

**Comment by Lucas-Maciel** [comment]
I also tried to run the combinatorial model with only one thread and I'm receiving this message:

Chromosome = SC_2648
HMM: number of states = 4
HMM: number of bins = 0
HMM: maximum number of iterations = 5000
HMM: maximum running time = none
HMM: epsilon = 0.01
HMM: number of experiments = 4
 Iteration              log(P)             dlog(P)    Time in sec
         0                -inf                   -              0
HMM: Precomputing densities ...
 Iteration              log(P)             dlog(P)    Time in sec
         0                -inf                   -              0

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: runMultivariate(bins = bins, info = p$info, comb.states = p$comb.states,     use.states = p$use.states, distributions = p$distributions,     weights = p$weights, correlationMatrix = p$correlationMatrix,     correlationMatrixInverse = p$correlationMatrixInverse, determinant = p$determinant,     max.iter = max.iter, max.time = max.time, eps = eps, num.threads = 1,     post.cutoff = post.cutoff, keep.posteriors = keep.posteriors,     keep.densities = keep.densities, verbosity = verbosity)
 2: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
 3: suppressMessages(runMultivariate(bins = bins, info = p$info,     comb.states = p$comb.states, use.states = p$use.states, distributions = p$distributions,     weights = p$weights, correlationMatrix = p$correlationMatrix,     correlationMatrixInverse = p$correlationMatrixInverse, determinant = p$determinant,     max.iter = max.iter, max.time = max.time, eps = eps, num.threads = 1,     post.cutoff = post.cutoff, keep.posteriors = keep.posteriors,     keep.densities = keep.densities, verbosity = verbosity))
 4: callPeaksMultivariate(files, use.states = states, max.states = conf[["max.states"]],     eps = conf[["eps.multivariate"]], max.iter = conf[["max.iter"]],     max.time = conf[["max.time"]], num.threads = conf[["numCPU"]],     per.chrom = conf[["per.chrom"]], keep.posteriors = conf[["keep.posteriors"]])
 5: Chromstar("/work/groups/schisto-th65-chipSeq/bowtie/nodup_samtools",     experiment_table, "/work/groups/schisto-th65-chipSeq/peakranger/chromstar/500_teste",     binsize = 500, min.mapq = 0, mode = "combinatorial")

**Comment by ataudt** [comment]
This problem is caused by chromosome SC_2648, which is probably smaller
than the specified binsize. As a fix, can you run your analysis only with
standard chromosomes? I have fixed this problem as well in the code, so you
might download the latest version from github and rerun your analysis.
