### ISSUE TITLE
Integration with other models or segmentations

### ISSUE THREAD

**Issue by josruirod** [ataudt/chromstaR#11]
Hi and thank you for the package, I'm going to definitely give it a try. 
I have a question, is thre any way segmentations coming from other approaches (i.e. ChromHMM) could be integrated in the analysis presented in the vignette?
I have inherited some segmentations and being able to apply for example the plotEnrichment function would be really interested

Either way, I'm going to use this package into my pipes from now own
Thank you for your time

**Comment by ataudt** [comment]
Below you can find a function that transforms a ChromHMM segmentation into chromstaR objects, which will allow you to use all available chromstaR functions. Please see the example code for how it works and adjust it accordingly.

#' Import ChromHMM segmentation
#' 
#' Import a chromatin state segmentation produced by ChromHMM as \code{\link{chromstaR-objects}}. This is useful to perform comparative analyses or simply use chromstaR plotting or enrichment functions on a ChromHMM segmentation.
#' 
#' The function takes the *segments.bed files, emissions_*.txt and transitions_*.txt files in \code{inputfolder}, and converts them into \code{\link{multiHMM}} objects for each condition that was specified in the \code{experiment.table}. All \code{\link{multiHMM}} objects are then combined into a \code{\link{combinedMultiHMM}} object and returned.
#' 
#' @param inputfolder Folder with ChromHMM output files (segmentation, emission and transition probabilities).
#' @param outputfolder Output folder for the converted \code{\link{chromstaR-objects}}.
#' @param assembly An assembly from which the chromosome lengths are determined. Please see \code{\link[GenomeInfoDb]{fetchExtendedChromInfoFromUCSC}} for available assemblies. Alternatively a data.frame generated by \code{\link[GenomeInfoDb]{fetchExtendedChromInfoFromUCSC}}.
#' @param binsize The bin size in base pairs used in ChromHMM.
#' @param experiment.table A \code{data.frame} or tab-separated text file with the structure of the experiment. See \code{\link{experiment.table}} for an example.
#' @param chrom.lengths A named character vector with chromosome lengths. Names correspond to chromosomes.
#' @param chromosomes A subset of chromosomes for which the bins are generated.
#' @param chromosome.format A character specifying the format of the chromosomes if \code{assembly} is specified. Either 'NCBI' for (1,2,3 ...) or 'UCSC' for (chr1,chr2,chr3 ...).
#' @return A \code{\link{combinedMultiHMM}} object. Intermediate \code{\link{multiHMM}} objects are saved to \code{outputfolder}.
#' 
#' @examples 
#'inputfolder <- "differential_CD4_numstates_16_binsize_1000bp"
#'outputfolder <- "testconvertChromHMM2chromstar"
#'assembly <- "mm9"
#'binsize <- 1000
#'chrom.lengths <- NULL
#'chromosomes <- paste0("chr", c(1:19, "X"))
#'chromosome.format <- "UCSC"
#'experiment.table <- "differential_CD4_numstates_16_binsize_1000bp/experiment_table_differential_CD4.tsv"
#'model <- importChromHMMsegmentation(inputfolder, outputfolder, assembly, binsize, experiment.table, chrom.lengths, chromosomes, chromosome.format)
#'
#'### Plot transition and emission probabilities of ChromHMM model ###
#'heatmapTransitionProbs(reorder.states=FALSE, transitionProbs=model$transitionProbs)
#'heatmapCombinations(emissionProbs = model$emissionProbs)
#'
#'### Use plotEnrichment function on imported ChromHMM segmentation ###
#'library(biomaRt)
#'ensembl <- useMart('ENSEMBL_MART_ENSEMBL', host='may2012.archive.ensembl.org',
#'                   dataset='mmusculus_gene_ensembl')
#'genes <- getBM(attributes=c('ensembl_gene_id', 'chromosome_name', 'start_position',
#'                            'end_position', 'strand', 'external_gene_id',
#'                            'gene_biotype'),
#'               mart=ensembl)
#'# Transform to GRanges for easier handling
#'genes <- GRanges(seqnames=paste0('chr',genes$chromosome_name),
#'                 ranges=IRanges(start=genes$start, end=genes$end),
#'                 strand=genes$strand,
#'                 name=genes$external_gene_id, biotype=genes$gene_biotype)
#'print(genes)
#'
#'ggplts <- plotEnrichment(model, annotation=genes)
#'ggplts[[1]] + facet_wrap(~combination)
#'
importChromHMMsegmentation <- function(inputfolder, outputfolder, assembly, binsize, experiment.table, chrom.lengths=NULL, chromosomes=NULL, chromosome.format="UCSC") {
  
    ## Make outputdir
    if (!file.exists(outputfolder)) { dir.create(outputfolder) }
  
    ## Read experiment table
    info <- NULL
    if (!is.null(experiment.table)) {
        info <- read.table(experiment.table, sep='\t', header=TRUE, comment.char='#')
        conditions <- unique(info$condition)
        info$ID <- paste0(info$mark, '-', info$condition, '-rep', info$replicate)
    }
    
    ## Prepare converting to chromstaR format
    bins <- chromstaR:::fixedWidthBins(assembly=assembly, chrom.lengths=chrom.lengths, chromosome.format=chromosome.format, binsizes=binsize, chromosomes=chromosomes)[[1]]
    
    ## Look for "segments.bed" files in inputfolder
    segfiles <- list.files(inputfolder, full.names=TRUE, pattern='segments.bed$')
    
    ## Loop over all conditions and save as chromstaR object for each condition
    for (cond in conditions) {
        savename <- file.path(outputfolder, paste0('multivariate_mode-combinatorial_condition-', cond, '_binsize', binsize, '_stepsize', binsize, '.RData'))
        if (!file.exists(savename)) {
            bedfile <- segfiles[grep(paste0(cond, '_'), basename(segfiles))]
            segs <- chromstaR::readCustomBedFile(bedfile, col.names=c('chromosome','start','end','state'), col.classes=c("character", "numeric", "numeric", "character"), skip=0, chromosome.format = chromosome.format)
            ind <- findOverlaps(bins, segs, select='first')
            ### Make return object ###
            result <- list()
            if (!is.null(info)) {
                result$info <- info[info$condition == cond,]
            } else {
                result$info <- NULL
            }
            ## Bin coordinates, posteriors and states
            result$bins <- bins
            result$bins$state <- factor(as.integer(sub('E','', segs$state[ind])))
            ## Add combinations
            result$bins$combination <- factor(segs$state[ind], levels=paste0('E',levels(result$bins$state)))
            ## Segmentation
            result$segments <- chromstaR:::multivariateSegmentation(result$bins, column2collapseBy='state')
            ## Parameters
            combinations <- levels(result$bins$combination)
            result$mapping <- NULL
            # Emission probabilities
            file <- list.files(inputfolder, full.names=TRUE, pattern='.*emissions_[0-9].*\\.txt')
            emissionProbs <- read.table(file, skip=0, row.names=1, sep='\t', header=TRUE)
            rownames(emissionProbs) <- paste0('E', rownames(emissionProbs))
            result$emissionProbs <- as.matrix(emissionProbs)
            # Transition probabilities
            file <- list.files(inputfolder, full.names=TRUE, pattern='.*transitions_[0-9].*\\.txt')
            transitionProbs <- read.table(file, skip=0, row.names=1, sep='\t', header=TRUE)
            rownames(transitionProbs) <- paste0('E', rownames(transitionProbs))
            colnames(transitionProbs) <- rownames(transitionProbs)
            result$transitionProbs <- as.matrix(transitionProbs)
            # Weights
            tstates <- table(result$bins$combination)
            result$weights <- sort(tstates/sum(tstates), decreasing=TRUE)
            ## Add class
            class(result) <- chromstaR:::class.multivariate.hmm
            
            message("Saving to file ", savename)
            save(result, file=savename)
        }
    }
    
    ## Combine multivariates
    savename.combined <- file.path(outputfolder, paste0('combined_mode-combinatorial_binsize', binsize, '_stepsize', binsize, '.RData'))
    if (!file.exists(savename.combined)) {
        multifiles <- list.files(outputfolder, full.names=TRUE, pattern='multivariate_mode-combinatorial')
        combined.model <- chromstaR::combineMultivariates(multifiles, mode='combinatorial')
        # Emission probabilities
        file <- list.files(inputfolder, full.names=TRUE, pattern='.*emissions_[0-9].*\\.txt')
        emissionProbs <- read.table(file, skip=0, row.names=1, sep='\t', header=TRUE)
        rownames(emissionProbs) <- paste0('E', rownames(emissionProbs))
        combined.model$emissionProbs <- as.matrix(emissionProbs)
        # Transition probabilities
        file <- list.files(inputfolder, full.names=TRUE, pattern='.*transitions_[0-9].*\\.txt')
        transitionProbs <- read.table(file, skip=0, row.names=1, sep='\t', header=TRUE)
        rownames(transitionProbs) <- paste0('E', rownames(transitionProbs))
        colnames(transitionProbs) <- rownames(transitionProbs)
        combined.model$transitionProbs <- as.matrix(transitionProbs)
        save(combined.model, file=savename.combined)
    } else {
        combined.model <- get(load(savename.combined))
    } 
    return(combined.model)
  
}

**Comment by josruirod** [comment]
Great, thank you so much for the resource

Regards

**Comment by josruirod** [comment]
Just one final question. I find very interesting the score 'diff.segments$differential.score', in order to be able to filter differences and get the regions with differences in n marks. When I'm importing chromhmm segmentations, diff.segments does not have differential.score. Is there any way to reproduce this score?

In any case I've bene able to use most of the original chromstar functions, thanks again

**Comment by ataudt** [comment]
The colum '$differential.score' is calculated from the posterior probabilities in the HMM output. In principle it is possible to calculate this as well for the ChromHMM posteriors, but I am not sure at the moment if ChromHMM reports the posterior probabilities for its model or if you have them available. If yes, it should basically be a matrix multiplication of the posteriors (dimensions bins x states) with the emission probabilities (dimensions states x marks) to obtain a matrix with posterior values per mark (dimensions bins x marks). From this matrix, the differential score is the sum of posteriors between marks (differences between conditions, then sum over marks).

**Comment by josruirod** [comment]
Appreciate the explanation. I think ChromHMM reports posterior probabilities when including a flag in LearnModel, so I'll look into it.
Thank you
