### ISSUE TITLE
Error in counts[, i1, ] <- hmm$bincounts$counts

### ISSUE THREAD

**Issue by zorrodong** [ataudt/chromstaR#14]
Hi, 
Thanks for the useful tool.

When I try to combine H3K4me1, H3K27ac and ATAC data, I got an error, see below:
however, H3K4me1 and H3K27ac is ok, H3K27ac and ATAC also got the error, so I guess it is the ATAC data that is problematic.

:
............
............
Getting coordinates ... 2.31s
Extracting read counts ...Error in counts[, i1, ] <- hmm$bincounts$counts : 
  number of items to replace is not a multiple of replacement length

.............
.............

Looking forward to your reply!

Zorro
20190726

**Comment by ataudt** [comment]
Hi Zorro,
can you send me a download link for the RData files that you are trying to combine and your script? I will reproduce this error and fix it, or in case smth is wrong with the ATAC data I will also be able to tell.
Regards,
Aaron

**Comment by HesbonAZN** [comment]
Hello Aaron,
Did you manage to get to the bottom of this issue? I am currently facing a similar error when I run H3K4me1, H3K27ac and STARR-seq data, but not with H3K4me1 and H3K27ac.

**Comment by ataudt** [comment]
Hi Hesbon, can you send me the lines of code that lead to the error? And the full console output?

**Comment by HesbonAZN** [comment]
Hi Aaron, 
Thank you for the prompt response.
As I am new to bioinformatics, please let me know if you need additional information or clarification.
**This is the experimental table**
> H3K4me1_H3K27ac_FAIRE_STARR_orig_sub_combinatorial_cr
                                           file    mark condition replicate
1                        A43_combined.nodup.bam H3K27ac   control         1
2                        A44_combined.nodup.bam H3K27ac   control         2
3 AZC90_R1_combined_AZC90_R2_combined.nodup.bam   FAIRE   control         1
4 AZC91_R1_combined_AZC91_R2_combined.nodup.bam   FAIRE   control         2
5                         Ren_H3K4me1_1_sub.bam H3K4me1   control         1
6                         Ren_H3K4me1_2_sub.bam H3K4me1   control         2
7                           AZT94sorted.bam.bam   STARR   control         1
8                           AZT95sorted.bam.bam   STARR   control         2
  pairedEndReads               controlFiles
1          FALSE A33_combined.nodup_sub.bam
2          FALSE A33_combined.nodup_sub.bam
3          FALSE                       <NA>
4          FALSE                       <NA>
5          FALSE A33_combined.nodup_sub.bam
6          FALSE A33_combined.nodup_sub.bam
7          FALSE                       <NA>
8          FALSE                       <NA>
**Then the peak calling** 
`Chromstar(inputfolder, experiment.table=H3K4me1_H3K27ac_FAIRE_STARR_orig_sub_combinatorial_cr, outputfolder=output_folder_H3K4me1_H3K27ac_FAIRE_STARR_sub_orig_cr_global, numCPU=8, binsize=1000, stepsize=500, mode='combinatorial')`
Setting up parallel execution with 8 threads ... 3.85s
================
Binning the data
================
Obtaining chromosome length information from file ~/projects/STARRseq/analysis/A43_combined.nodup.bam ... 0.13s
Making fixed-width bins for bin size 1000 ... 2.06s
Making fixed-width bins for bin size 500 ... 4.37s
Binning data ... 7.3s
Binning input ... 4.54s
========================
Calling univariate peaks
========================
Univariate peak calling ... 114.83s
==========================
Calling multivariate peaks
==========================
mode = combinatorial
======
condition = control
======
Getting coordinates ... 0.96s
Extracting read counts ...Error in counts[, i1, ] <- hmm$bincounts$counts : number of items to replace is not a multiple of replacement length

**Comment by ataudt** [comment]
Hi Hesbon,
please excuse the delay in my response. I would guess that the STARR-seq in condition control might have not enough reads for peak calling? To debug precisely what is going on, I would like to ask you to send me the folder 
output_folder_H3K4me1_H3K27ac_FAIRE_STARR_sub_orig_cr_global/**univariate**

Best regards,
Aaron

**Comment by HesbonAZN** [comment]
Hello Aaron,
Thank you for the response.
Since the ../univariate folder is large ~ 1.2GB can I send you the STARR-seq .RData file?
I have attached those here.

Regards,

Hesbon
________________________________

**Comment by ataudt** [comment]
Hi Hesbon,
it looks like only chromosome 12 has peak calls, the other chromosomes are empty. Is this intended? Did you run Chromstar(..., chromosomes='chr12') ?

**Comment by ataudt** [comment]
Closed due to inactivity
