### ISSUE TITLE
Error when running Differential Mode for chromatin states

### ISSUE THREAD

**Issue by rm1238** [ataudt/chromstaR#16]
Hello again,

I am trying to run the following command on chromstaR and am getting the following error:

> Chromstar(inputfolder = inputfolder,
          experiment.table = sampleTable,
          outputfolder = outputfolder,
          numCPU = 4,
          mode= "differential",
          binsize = 200,
          eps.univariate = 0.01,
          eps.multivariate = 0.01)

Here is the output with the error (error is highlighted at the end of text):

Setting up parallel execution with 4 threads ... 0.96s
================
Binning the data
================
Obtaining chromosome length information from file .//EV_K27ac_1_dedup_blacklisted_merge.bam ... 0.03s
Making fixed-width bins for bin size 200 ... 6.85s
Making fixed-width bins for bin size 100 ... 14.28s
Binning data ... 14.07s
Binning control ... 8.37s
========================
Calling univariate peaks
========================
Univariate peak calling ... 0.1s
==========================
Calling multivariate peaks
==========================
mode = differential
------------
mark = K27ac
------------
------------
mark = K4me1
------------
===========================
Combining multivariate HMMs
===========================
Processing HMM 1 ... 112.32s
Processing HMM 2 ... 108.74s
Concatenating HMMs ... 94.04s
Making combinations ... 124.04s
Reassigning levels ... 5.19s
Assigning transition groups ... 28.06s
Assigning combinatorial states ... 1.55s
Transferring counts and posteriors ... 5.46s
Making segmentation ... 165.73s
Adding differential score ... 0.47s
Getting maximum posterior in peaks ... 17.1s
**Redoing segmentation for each condition separately ...Error: subscript contains invalid names**

Any help with how to sort out this issue would be most appreciated.

Ricardo

**Comment by ataudt** [comment]
Hi Ricardo,
the reason for the error are the spaces in the condition column of the experiment table. Please change "Day 0" to "Day0" and it will work.

There should have been a check in place to intercept such input, but unfortunately it didn't check for spaces properly. I will fix this in the next release.
Thank you for submitting that bug.
Cheers,Aaron
