### ISSUE TITLE
Additional options

### ISSUE THREAD

**Issue by devmotion** [ataudt/chromstaR#3]
Hej Aaron!

I added two additional options to my fork of chromstaR, one for keeping the posteriors per state (and not only per sample, as already possible) and one for blacklisting certain genomic ranges (i.e. removing overlapping bins before any analysis; this was already partly implemented). If you'd like to add these options to chromstaR I'll happily send you my code/file a pull request.

Something I discovered while studying `bedimport.R`: according to [UCSC](https://genome.ucsc.edu/FAQ/FAQformat.html#format1) 

> the first 100 bases of a chromosome are defined as chromStart=0, chromEnd=100, and span the bases numbered 0-99. 

I.e. (as mentioned in `export.R`) one has to convert half-open zero-based intervals to closed one-based intervals when importing bed files. So shouldn't it instead of

``` R
ranges=IRanges(start=data[,2]+1, end=data[,3]+1)
```

in `bedimport.R` rather be

``` R
ranges=IRanges(start=data[,2]+1, end=data[,3])
```

?

**Comment by ataudt** [comment]
Hi David,

as for the ranges, you are correct, it should be

ranges=IRanges(start=data[,2]+1, end=data[,3])

I will change it in my code.

Maybe we can arrange a meeting this or next week to discuss what exactly you are using chromstaR for? I am very curious.

Cheers,
Aaron

**Comment by devmotion** [comment]
Great :+1: 

I'm at the ICB the whole week and available pretty much all the time (besides the institute talks and meetings :smile:). Just tell me when it suits you or drop by at the student room!
